# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sync_service.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'sync_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12sync_service.proto\x12\x0csync_service\"\x92\x01\n\x13SyncResourceRequest\x12\x12\n\nevent_type\x18\x01 \x01(\t\x12\x15\n\rresource_type\x18\x02 \x01(\t\x12\x11\n\tnamespace\x18\x03 \x01(\t\x12\x0c\n\x04name\x18\x04 \x01(\t\x12\x0f\n\x07\x63luster\x18\x05 \x01(\t\x12\x0b\n\x03uid\x18\x06 \x01(\t\x12\x11\n\tdata_json\x18\x07 \x01(\t\"8\n\x14SyncResourceResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"i\n\x14SyncNamespaceRequest\x12\x12\n\nevent_type\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07\x63luster\x18\x03 \x01(\t\x12\x0b\n\x03uid\x18\x04 \x01(\t\x12\x11\n\tdata_json\x18\x05 \x01(\t\"9\n\x15SyncNamespaceResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xbe\x01\n\x0bSyncService\x12U\n\x0cSyncResource\x12!.sync_service.SyncResourceRequest\x1a\".sync_service.SyncResourceResponse\x12X\n\rSyncNamespace\x12\".sync_service.SyncNamespaceRequest\x1a#.sync_service.SyncNamespaceResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sync_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SYNCRESOURCEREQUEST']._serialized_start=37
  _globals['_SYNCRESOURCEREQUEST']._serialized_end=183
  _globals['_SYNCRESOURCERESPONSE']._serialized_start=185
  _globals['_SYNCRESOURCERESPONSE']._serialized_end=241
  _globals['_SYNCNAMESPACEREQUEST']._serialized_start=243
  _globals['_SYNCNAMESPACEREQUEST']._serialized_end=348
  _globals['_SYNCNAMESPACERESPONSE']._serialized_start=350
  _globals['_SYNCNAMESPACERESPONSE']._serialized_end=407
  _globals['_SYNCSERVICE']._serialized_start=410
  _globals['_SYNCSERVICE']._serialized_end=600
# @@protoc_insertion_point(module_scope)
